version: "3.4"

services:
    mongodb:
        container_name: docker_mongodb_bookstore
        image: mongo:4
        volumes:
            - mongodb_data:/data/db
        ports:
            - "27017:27017"
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: username
            MONGO_INITDB_ROOT_PASSWORD: password

volumes:
    mongodb_data:
